# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: xxx
      MONGO_INITDB_ROOT_PASSWORD: xxx

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: xxx
      ME_CONFIG_MONGODB_ADMINPASSWORD: xxx
      ME_CONFIG_MONGODB_URL: xxxxx